name: flutter_and_firebase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.22.1 <3.0.0'

dependencies:
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  localstorage: ^4.0.1+2
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  # sound_stream: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
